production:
  auto_create: false
  deny_delete: true
  svn:
    path: /var/lib/svn
    svnadmin: /usr/bin/svnadmin
    hooks: /usr/share/subversion/hook-scripts
    url: svn
  git:
    path: /var/lib/git
    git: /usr/bin/git
    options: --bare
    url: http://git.myhost.com
    update_server_info: true
    git_ext: true
    hooks: /usr/share/git/hooks
  mercurial:
    path: /var/lib/mercurial
    hg: /usr/bin/hg
    hgrc: /etc/mercurial/hgrc

development:
